IF EXISTS (SELECT * FROM sys.procedures WHERE name='sp_employee_save') 
BEGIN
   DROP PROCEDURE  dbo.sp_employee_save
END
GO
CREATE PROCEDURE  dbo.sp_employee_save
@employee_id INT,
@first_name NVARCHAR(50),
@last_name NVARCHAR(50),
@user_name NVARCHAR(50),
@password NVARCHAR(max),
@name_prefix VARCHAR(7),
@middle_initial VARCHAR(2),
@gender VARCHAR(2),
@email NVARCHAR(50),
@father_name NVARCHAR(50),
@mother_name NVARCHAR(50),
@mother_maiden_name NVARCHAR(50),
@date_of_birth DATE,
@time_of_birth TIME,
@age_in_years FLOAT,
@weight_in_kgs FLOAT,
@date_of_joining DATETIME2,
@quarter_of_joining VARCHAR(2),
@half_of_joining VARCHAR(2),
@year_of_joining INT,
@month_of_joining INT,
@month_name_of_joining VARCHAR(15),
@short_month VARCHAR(5),
@day_of_joining INT,
@dow_of_joining VARCHAR(15),
@short_dow VARCHAR(5),
@age_in_company_in_years FLOAT,
@salary DECIMAL,
@ssn NVARCHAR(50),
@last_hike NVARCHAR(10),
@phone_number VARCHAR(20),
@place_name NVARCHAR(50),
@county NVARCHAR(50),
@city NVARCHAR(50),
@state NVARCHAR(50),
@zip NVARCHAR(50),
@region NVARCHAR(50)

AS

BEGIN
 INSERT INTO employee  
( employee_id ,
 first_name ,
 last_name ,
 user_name ,
 password ,
 name_prefix ,
 middle_initial ,
 gender ,
 email ,
 father_name,
 mother_name ,
  mother_maiden_name ,
 date_of_birth ,
 time_of_birth ,
 age_in_years ,
 weight_in_kgs ,
 date_of_joining ,
 quarter_of_joining ,
 half_of_joining ,
 year_of_joining ,
 month_of_joining ,
 month_name_of_joining ,
 short_month ,
 day_of_joining ,
 dow_of_joining ,
 short_dow ,
 age_in_company_in_years ,
 salary ,
 ssn ,
 last_hike,
 phone_number ,
 place_name ,
 county ,
 city ,
 state ,
 zip,
 region  )  
VALUES (
@employee_id ,
@first_name ,
@last_name ,
@user_name ,
@password ,
@name_prefix ,
@middle_initial ,
@gender ,
@email ,
@father_name,
@mother_name ,
@mother_maiden_name ,
@date_of_birth ,
@time_of_birth ,
@age_in_years ,
@weight_in_kgs ,
@date_of_joining ,
@quarter_of_joining ,
@half_of_joining ,
@year_of_joining ,
@month_of_joining ,
@month_name_of_joining ,
@short_month ,
@day_of_joining ,
@dow_of_joining ,
@short_dow ,
@age_in_company_in_years ,
@salary ,
@ssn ,
@last_hike,
@phone_number ,
@place_name ,
@county ,
@city ,
@state ,
@zip,
@region
)
END
GO